INSERT OR IGNORE INTO problems (id, category, problem_name, problem_url, genre, difficulty_level) VALUES
(1, 'LeetCode', 'Contains Duplicate', 'https://leetcode.com/problems/contains-duplicate/description/', 'Array & Hashing', 'Easy'),
(2, 'LeetCode', 'Valid Anagram', 'https://leetcode.com/problems/valid-anagram/', 'Array & Hashing', 'Easy'),
(3, 'LeetCode', 'Two Sum', 'https://leetcode.com/problems/two-sum/description/', 'Array & Hashing', 'Easy'),
(4, 'LeetCode', 'Intersection of Two Arrays', 'https://leetcode.com/problems/intersection-of-two-arrays/', 'Array & Hashing', 'Easy'),
(5, 'LeetCode', 'Unique Email Addresses', 'https://leetcode.com/problems/unique-email-addresses/', 'Array & Hashing', 'Easy'),
(6, 'LeetCode', 'First Unique Character in a String', 'https://leetcode.com/problems/first-unique-character-in-a-string/', 'Array & Hashing', 'Easy'),
(7, 'LeetCode', 'Group Anagrams', 'https://leetcode.com/problems/group-anagrams/description/', 'Array & Hashing', 'Medium'),
(8, 'LeetCode', 'Top K Frequent Elements', 'https://leetcode.com/problems/top-k-frequent-elements/description/', 'Array & Hashing', 'Medium'),
(9, 'LeetCode', 'Product of Array Except Self', 'https://leetcode.com/problems/product-of-array-except-self/description/', 'Array & Hashing', 'Medium'),
(10, 'LeetCode', 'Valid Sudoku', 'https://leetcode.com/problems/valid-sudoku/', 'Array & Hashing', 'Medium'),
(11, 'LeetCode', 'Longest Consecutive Sequence', 'https://leetcode.com/problems/longest-consecutive-sequence/description/', 'Array & Hashing', 'Medium'),
(12, 'LeetCode', 'Subarray Sum Equals K', 'https://leetcode.com/problems/subarray-sum-equals-k/', 'Array & Hashing', 'Medium'),
(13, 'LeetCode', 'Valid Palindrome', 'https://leetcode.com/problems/valid-palindrome/', 'Two Pointers', 'Easy'),
(14, 'LeetCode', 'Two Sum II Input Array Is Sorted', 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/description/', 'Two Pointers', 'Medium'),
(15, 'LeetCode', '3Sum', 'https://leetcode.com/problems/3sum/description/', 'Two Pointers', 'Medium'),
(16, 'LeetCode', 'Container With Most Water', 'https://leetcode.com/problems/container-with-most-water/description/', 'Two Pointers', 'Medium'),
(17, 'LeetCode', 'Valid Parentheses', 'https://leetcode.com/problems/valid-parentheses/', 'Stack', 'Easy'),
(18, 'LeetCode', 'Min Stack', 'https://leetcode.com/problems/min-stack/description/', 'Stack', 'Medium'),
(19, 'LeetCode', 'Evaluate Reverse Polish Notation', 'https://leetcode.com/problems/evaluate-reverse-polish-notation/description/', 'Stack', 'Medium'),
(20, 'LeetCode', 'Generate Parentheses', 'https://leetcode.com/problems/generate-parentheses/description/', 'Stack', 'Medium'),
(21, 'LeetCode', 'Daily Temperatures', 'https://leetcode.com/problems/daily-temperatures/description/', 'Stack', 'Medium'),
(22, 'LeetCode', 'Car Fleet', 'https://leetcode.com/problems/car-fleet/description/', 'Stack', 'Medium'),
(23, 'LeetCode', 'Binary Search', 'https://leetcode.com/problems/binary-search/', 'Binary Search', 'Easy'),
(24, 'LeetCode', 'Minimum Depth of Binary Tree', 'https://leetcode.com/problems/minimum-depth-of-binary-tree/', 'Binary Search', 'Easy'),
(25, 'LeetCode', 'Merge Two Binary Trees', 'https://leetcode.com/problems/merge-two-binary-trees/', 'Binary Search', 'Easy'),
(26, 'LeetCode', 'Convert Sorted Array to Binary Search Tree', 'https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/', 'Binary Search', 'Easy'),
(27, 'LeetCode', 'Path Sum', 'https://leetcode.com/problems/path-sum/', 'Binary Search', 'Easy'),
(28, 'LeetCode', 'Search Insert Position', 'https://leetcode.com/problems/search-insert-position/', 'Binary Search', 'Easy'),
(29, 'LeetCode', 'Search a 2D Matrix', 'https://leetcode.com/problems/search-a-2d-matrix/', 'Binary Search', 'Medium'),
(30, 'LeetCode', 'Koko Eating Bananas', 'https://leetcode.com/problems/koko-eating-bananas/', 'Binary Search', 'Medium'),
(31, 'LeetCode', 'Find Minimum In Rotated Sorted Array', 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/', 'Binary Search', 'Medium'),
(32, 'LeetCode', 'Search In Rotated Sorted Array', 'https://leetcode.com/problems/search-in-rotated-sorted-array/', 'Binary Search', 'Medium'),
(33, 'LeetCode', 'Time Based Key Value Store', 'https://leetcode.com/problems/time-based-key-value-store/', 'Binary Search', 'Medium'),
(34, 'LeetCode', 'Binary Tree Zigzag Level Order Traversal', 'https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/', 'Binary Search', 'Medium'),
(35, 'LeetCode', 'Binary Tree Level Order Traversal', 'https://leetcode.com/problems/binary-tree-level-order-traversal/', 'Binary Search', 'Medium'),
(36, 'LeetCode', 'Best Time to Buy And Sell Stock', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/', 'Sliding Window', 'Easy'),
(37, 'LeetCode', 'Longest Substring Without Repeating Characters', 'https://leetcode.com/problems/longest-substring-without-repeating-characters/', 'Sliding Window', 'Medium'),
(38, 'LeetCode', 'Longest Repeating Character Replacement', 'https://leetcode.com/problems/longest-repeating-character-replacement/', 'Sliding Window', 'Medium'),
(39, 'LeetCode', 'Permutation In String', 'https://leetcode.com/problems/permutation-in-string/', 'Sliding Window', 'Medium'),
(40, 'LeetCode', 'Minimum Size Subarray Sum', 'https://leetcode.com/problems/minimum-size-subarray-sum/', 'Sliding Window', 'Medium'),
(41, 'LeetCode', 'Reverse Linked List', 'https://leetcode.com/problems/reverse-linked-list/', 'Linked List', 'Easy'),
(42, 'LeetCode', 'Merge Two Sorted Lists', 'https://leetcode.com/problems/merge-two-sorted-lists/', 'Linked List', 'Easy'),
(43, 'LeetCode', 'Linked List Cycle', 'https://leetcode.com/problems/linked-list-cycle/', 'Linked List', 'Easy'),
(44, 'LeetCode', 'Linked List Cycle II', 'https://leetcode.com/problems/linked-list-cycle-ii/', 'Linked List', 'Easy'),
(45, 'LeetCode', 'Reorder List', 'https://leetcode.com/problems/reorder-list/', 'Linked List', 'Medium'),
(46, 'LeetCode', 'Remove Nth Node From End of List', 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/', 'Linked List', 'Medium'),
(47, 'LeetCode', 'Copy List With Random Pointer', 'https://leetcode.com/problems/copy-list-with-random-pointer/', 'Linked List', 'Medium'),
(48, 'LeetCode', 'Add Two Numbers', 'https://leetcode.com/problems/add-two-numbers/', 'Linked List', 'Medium'),
(49, 'LeetCode', 'Find The Duplicate Number', 'https://leetcode.com/problems/find-the-duplicate-number/', 'Linked List', 'Medium'),
(50, 'LeetCode', 'LRU Cache', 'https://leetcode.com/problems/lru-cache/', 'Linked List', 'Medium'),
(51, 'LeetCode', 'Remove Duplicates from Sorted List', 'https://leetcode.com/problems/remove-duplicates-from-sorted-list/', 'Linked List', 'Medium'),
(52, 'LeetCode', 'Remove Duplicates from Sorted List II', 'https://leetcode.com/problems/remove-duplicates-from-sorted-list-ii/description/', 'Linked List', 'Medium'),
(53, 'LeetCode', 'Invert Binary Tree', 'https://leetcode.com/problems/invert-binary-tree/', 'Trees', 'Easy'),
(54, 'LeetCode', 'Maximum Depth of Binary Tree', 'https://leetcode.com/problems/maximum-depth-of-binary-tree/', 'Trees', 'Easy'),
(55, 'LeetCode', 'Diameter of Binary Tree', 'https://leetcode.com/problems/diameter-of-binary-tree/', 'Trees', 'Easy'),
(56, 'LeetCode', 'Balanced Binary Tree', 'https://leetcode.com/problems/balanced-binary-tree/', 'Trees', 'Easy'),
(57, 'LeetCode', 'Same Tree', 'https://leetcode.com/problems/same-tree/', 'Trees', 'Easy'),
(58, 'LeetCode', 'Subtree of Another Tree', 'https://leetcode.com/problems/subtree-of-another-tree/', 'Trees', 'Easy'),
(59, 'LeetCode', 'Lowest Common Ancestor of a Binary Search Tree', 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/', 'Trees', 'Medium'),
(60, 'LeetCode', 'Binary Tree Right Side View', 'https://leetcode.com/problems/binary-tree-right-side-view/', 'Trees', 'Medium'),
(61, 'LeetCode', 'Count Good Nodes In Binary Tree', 'https://leetcode.com/problems/count-good-nodes-in-binary-tree/', 'Trees', 'Medium'),
(62, 'LeetCode', 'Validate Binary Search Tree', 'https://leetcode.com/problems/validate-binary-search-tree/', 'Trees', 'Medium'),
(63, 'LeetCode', 'Kth Smallest Element In a Bst', 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/', 'Trees', 'Medium'),
(64, 'LeetCode', 'Construct Binary Tree From Preorder And Inorder Traversal', 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/', 'Trees', 'Medium'),
(65, 'LeetCode', 'Implement Trie Prefix Tree', 'https://leetcode.com/problems/implement-trie-prefix-tree/', 'Tries', 'Medium'),
(66, 'LeetCode', 'Design Add And Search Words Data Structure', 'https://leetcode.com/problems/design-add-and-search-words-data-structure/', 'Tries', 'Medium'),
(67, 'LeetCode', 'Subsets', 'https://leetcode.com/problems/subsets/', 'Backtracking', 'Medium'),
(68, 'LeetCode', 'Combination Sum', 'https://leetcode.com/problems/combination-sum/', 'Backtracking', 'Medium'),
(69, 'LeetCode', 'Permutations', 'https://leetcode.com/problems/permutations/', 'Backtracking', 'Medium'),
(70, 'LeetCode', 'Subsets II', 'https://leetcode.com/problems/subsets-ii/', 'Backtracking', 'Medium'),
(71, 'LeetCode', 'Combination Sum II', 'https://leetcode.com/problems/combination-sum-ii/', 'Backtracking', 'Medium'),
(72, 'LeetCode', 'Word Search', 'https://leetcode.com/problems/word-search/', 'Backtracking', 'Medium'),
(73, 'LeetCode', 'Palindrome Partitioning', 'https://leetcode.com/problems/palindrome-partitioning/', 'Backtracking', 'Medium'),
(74, 'LeetCode', 'Letter Combinations of a Phone Number', 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/', 'Backtracking', 'Medium'),
(75, 'LeetCode', 'Kth Largest Element In a Stream', 'https://leetcode.com/problems/kth-largest-element-in-a-stream/', 'Heap / Priority Queue', 'Easy'),
(76, 'LeetCode', 'Last Stone Weight', 'https://leetcode.com/problems/last-stone-weight/', 'Heap / Priority Queue', 'Easy'),
(77, 'LeetCode', 'K Closest Points to Origin', 'https://leetcode.com/problems/k-closest-points-to-origin/', 'Heap / Priority Queue', 'Medium'),
(78, 'LeetCode', 'Kth Largest Element In An Array', 'https://leetcode.com/problems/kth-largest-element-in-an-array/', 'Heap / Priority Queue', 'Medium'),
(79, 'LeetCode', 'Task Scheduler', 'https://leetcode.com/problems/task-scheduler/', 'Heap / Priority Queue', 'Medium'),
(80, 'LeetCode', 'Design Twitter', 'https://leetcode.com/problems/design-twitter/', 'Heap / Priority Queue', 'Medium'),
(81, 'LeetCode', 'Number of Islands', 'https://leetcode.com/problems/number-of-islands/', 'Graphs', 'Medium'),
(82, 'LeetCode', 'Clone Graph', 'https://leetcode.com/problems/clone-graph/', 'Graphs', 'Medium'),
(83, 'LeetCode', 'Max Area of Island', 'https://leetcode.com/problems/max-area-of-island/', 'Graphs', 'Medium'),
(84, 'LeetCode', 'Pacific Atlantic Water Flow', 'https://leetcode.com/problems/pacific-atlantic-water-flow/', 'Graphs', 'Medium'),
(85, 'LeetCode', 'Surrounded Regions', 'https://leetcode.com/problems/surrounded-regions/', 'Graphs', 'Medium'),
(86, 'LeetCode', 'Rotting Oranges', 'https://leetcode.com/problems/rotting-oranges/', 'Graphs', 'Medium'),
(87, 'LeetCode', 'Course Schedule', 'https://leetcode.com/problems/course-schedule/', 'Graphs', 'Medium'),
(88, 'LeetCode', 'Course Schedule II', 'https://leetcode.com/problems/course-schedule-ii/', 'Graphs', 'Medium'),
(89, 'LeetCode', 'Redundant Connection', 'https://leetcode.com/problems/redundant-connection/', 'Graphs', 'Medium'),
(90, 'LeetCode', 'Number of Connected Components in an Undirected Graph', 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/', 'Graphs', 'Medium'),
(91, 'LeetCode', 'Climbing Stairs', 'https://leetcode.com/problems/climbing-stairs/', '1-D DP', 'Easy'),
(92, 'LeetCode', 'Min Cost Climbing Stairs', 'https://leetcode.com/problems/min-cost-climbing-stairs/', '1-D DP', 'Easy'),
(93, 'LeetCode', 'House Robber', 'https://leetcode.com/problems/house-robber/', '1-D DP', 'Easy'),
(94, 'LeetCode', 'Best Time to Buy and Sell Stock II', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/', '1-D DP', 'Easy'),
(95, 'LeetCode', 'House Robber II', 'https://leetcode.com/problems/house-robber-ii/', '1-D DP', 'Medium'),
(96, 'LeetCode', 'Longest Palindromic Substring', 'https://leetcode.com/problems/longest-palindromic-substring/', '1-D DP', 'Medium'),
(97, 'LeetCode', 'Palindromic Substrings', 'https://leetcode.com/problems/palindromic-substrings/', '1-D DP', 'Medium'),
(98, 'LeetCode', 'Decode Ways', 'https://leetcode.com/problems/decode-ways/', '1-D DP', 'Medium'),
(99, 'LeetCode', 'Coin Change', 'https://leetcode.com/problems/coin-change/', '1-D DP', 'Medium'),
(100, 'LeetCode', 'Maximum Product Subarray', 'https://leetcode.com/problems/maximum-product-subarray/', '1-D DP', 'Medium'),
(101, 'LeetCode', 'Word Break', 'https://leetcode.com/problems/word-break/', '1-D DP', 'Medium'),
(102, 'LeetCode', 'Longest Increasing Subsequence', 'https://leetcode.com/problems/longest-increasing-subsequence/', '1-D DP', 'Medium'),
(103, 'LeetCode', 'Partition Equal Subset Sum', 'https://leetcode.com/problems/partition-equal-subset-sum/', '1-D DP', 'Medium'),
(104, 'LeetCode', 'Insert Interval', 'https://leetcode.com/problems/insert-interval/', 'Intervals', 'Medium'),
(105, 'LeetCode', 'Merge Intervals', 'https://leetcode.com/problems/merge-intervals/', 'Intervals', 'Medium'),
(106, 'LeetCode', 'Non Overlapping Intervals', 'https://leetcode.com/problems/non-overlapping-intervals/', 'Intervals', 'Medium'),
(107, 'LeetCode', 'Maximum Subarray', 'https://leetcode.com/problems/maximum-subarray/', 'Greedy', 'Medium'),
(108, 'LeetCode', 'Jump Game', 'https://leetcode.com/problems/jump-game/', 'Greedy', 'Medium'),
(109, 'LeetCode', 'Jump Game II', 'https://leetcode.com/problems/jump-game-ii/', 'Greedy', 'Medium'),
(110, 'LeetCode', 'Gas Station', 'https://leetcode.com/problems/gas-station/', 'Greedy', 'Medium'),
(111, 'LeetCode', 'Hand of Straights', 'https://leetcode.com/problems/hand-of-straights/', 'Greedy', 'Medium'),
(112, 'LeetCode', 'Merge Triplets to Form Target Triplet', 'https://leetcode.com/problems/merge-triplets-to-form-target-triplet/', 'Greedy', 'Medium'),
(113, 'LeetCode', 'Partition Labels', 'https://leetcode.com/problems/partition-labels/', 'Greedy', 'Medium'),
(114, 'LeetCode', 'Valid Parenthesis String', 'https://leetcode.com/problems/valid-parenthesis-string/', 'Greedy', 'Medium'),
(115, 'LeetCode', 'Min Cost to Connect All Points', 'https://leetcode.com/problems/min-cost-to-connect-all-points/', 'Advanced Graphs', 'Medium'),
(116, 'LeetCode', 'Network Delay Time', 'https://leetcode.com/problems/network-delay-time/', 'Advanced Graphs', 'Medium'),
(117, 'LeetCode', 'Cheapest Flights Within K Stops', 'https://leetcode.com/problems/cheapest-flights-within-k-stops/', 'Advanced Graphs', 'Medium'),
(118, 'LeetCode', 'Unique Paths', 'https://leetcode.com/problems/unique-paths/', '2-D DP', 'Medium'),
(119, 'LeetCode', 'Longest Common Subsequence', 'https://leetcode.com/problems/longest-common-subsequence/', '2-D DP', 'Medium'),
(120, 'LeetCode', 'Best Time to Buy And Sell Stock With Cooldown', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/', '2-D DP', 'Medium'),
(121, 'LeetCode', 'Coin Change II', 'https://leetcode.com/problems/coin-change-ii/', '2-D DP', 'Medium'),
(122, 'LeetCode', 'Target Sum', 'https://leetcode.com/problems/target-sum/', '2-D DP', 'Medium'),
(123, 'LeetCode', 'Interleaving String', 'https://leetcode.com/problems/interleaving-string/', '2-D DP', 'Medium'),
(124, 'LeetCode', 'Edit Distance', 'https://leetcode.com/problems/edit-distance/', '2-D DP', 'Medium'),
(125, 'LeetCode', 'Unique Paths II', 'https://leetcode.com/problems/unique-paths-ii/', '2-D DP', 'Medium'),
(126, 'LeetCode', 'Single Number', 'https://leetcode.com/problems/single-number/', 'Bit Manipulation', 'Easy'),
(127, 'LeetCode', 'Number of 1 Bits', 'https://leetcode.com/problems/number-of-1-bits/', 'Bit Manipulation', 'Easy'),
(128, 'LeetCode', 'Counting Bits', 'https://leetcode.com/problems/counting-bits/', 'Bit Manipulation', 'Easy'),
(129, 'LeetCode', 'Reverse Bits', 'https://leetcode.com/problems/reverse-bits/', 'Bit Manipulation', 'Easy'),
(130, 'LeetCode', 'Missing Number', 'https://leetcode.com/problems/missing-number/', 'Bit Manipulation', 'Easy'),
(131, 'LeetCode', 'Sum of Two Integers', 'https://leetcode.com/problems/sum-of-two-integers/', 'Bit Manipulation', 'Medium'),
(132, 'LeetCode', 'Reverse Integer', 'https://leetcode.com/problems/reverse-integer/', 'Bit Manipulation', 'Medium'),
(133, 'LeetCode', 'Happy Number', 'https://leetcode.com/problems/happy-number/', 'Math & Geometry', 'Easy'),
(134, 'LeetCode', 'Plus One', 'https://leetcode.com/problems/plus-one/', 'Math & Geometry', 'Easy'),
(135, 'LeetCode', 'Rotate Image', 'https://leetcode.com/problems/rotate-image/', 'Math & Geometry', 'Medium'),
(136, 'LeetCode', 'Spiral Matrix', 'https://leetcode.com/problems/spiral-matrix/', 'Math & Geometry', 'Medium'),
(137, 'LeetCode', 'Set Matrix Zeroes', 'https://leetcode.com/problems/set-matrix-zeroes/', 'Math & Geometry', 'Medium'),
(138, 'LeetCode', 'Pow(x, n)', 'https://leetcode.com/problems/powx-n/', 'Math & Geometry', 'Medium'),
(139, 'LeetCode', 'Multiply Strings', 'https://leetcode.com/problems/multiply-strings/', 'Math & Geometry', 'Medium'),
(140, 'LeetCode', 'Detect Squares', 'https://leetcode.com/problems/detect-squares/', 'Math & Geometry', 'Medium'),
(141, 'LeetCodeを解く会', 'Assign Cookies', 'https://leetcode.com/problems/assign-cookies/description/', 'Greedy + Backtracking', 'Easy'),
(142, 'LeetCodeを解く会', "Pascal's Triangle", 'https://leetcode.com/problems/pascals-triangle/description/', 'Dynamic Programming', 'Easy'),
(143, 'LeetCodeを解く会', 'Majority Element', 'https://leetcode.com/problems/majority-element/description/', 'HashMap', 'Easy'),
(144, 'LeetCodeを解く会', 'Intersection of Two Linked Lists', 'https://leetcode.com/problems/intersection-of-two-linked-lists/description/', 'LinkedList', 'Easy'),
(145, 'LeetCodeを解く会', 'Search in a Binary Search Tree', 'https://leetcode.com/problems/search-in-a-binary-search-tree/description/', 'Tree, BST', 'Easy'),
(146, 'LeetCodeを解く会', 'Minimum Number Game', 'https://leetcode.com/problems/minimum-number-game/description/', 'Heap, PriorityQueue', 'Easy'),
(147, 'LeetCodeを解く会', 'Find K Pairs with Smallest Sums', 'https://leetcode.com/problems/find-k-pairs-with-smallest-sums/', 'Heap, PriorityQueue', 'Medium'),
(148, 'LeetCodeを解く会', 'Word Ladder', 'https://leetcode.com/problems/word-ladder/', 'Graph, BFS, DFS', 'Medium'),
(149, 'LeetCodeを解く会', 'Capacity To Ship Packages Within D Days', 'https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/', 'Binary Search', 'Medium'),
(150, 'LeetCodeを解く会', 'K-th Symbol in Grammar', 'https://leetcode.com/problems/k-th-symbol-in-grammar/', 'Recursion', 'Medium'),
(151, 'LeetCodeを解く会', 'Split BST', 'https://leetcode.com/problems/split-bst/', 'Recursion', 'Medium'),
(152, 'LeetCodeを解く会', 'Meeting Rooms II', 'https://leetcode.com/problems/meeting-rooms-ii/', 'Others', 'Medium'),
(153, 'LeetCodeを解く会', 'Is Subsequence', 'https://leetcode.com/problems/is-subsequence/', 'Others', 'Medium'),
(154, 'LeetCodeを解く会', 'Next Permutation', 'https://leetcode.com/problems/next-permutation/', 'Others', 'Medium'),
(155, 'LeetCodeを解く会', 'String to Integer (atoi)', 'https://leetcode.com/problems/string-to-integer-atoi/', 'Others', 'Medium'),
(156, 'LeetCodeを解く会', 'ZigZag Conversion', 'https://leetcode.com/problems/zigzag-conversion/', 'Others', 'Medium');